# Output directory (relative).
out-dir = "../current"
# Go name of package.
package = "github.com/hajimehoshi/ebiten/v2"
# Go semantic version of package.
version = "v2.7.8"
# Auto-remove "New" part of functions (e.g. widget.NewLabel => widget-label, app.New => app).
cut-new = true
# Build flag used to enable binding. * is replaced by package name.
build-flag = "b_*"

## Descending priority. Packages not listed will always be prefixed.
## In case of conflicting function names, only the function from the
## package with the highest priority is not prefixed.
no-prefix = [
    "github.com/hajimehoshi/ebiten/v2",
    "github.com/hajimehoshi/ebiten/v2/audio",
    "github.com/hajimehoshi/ebiten/v2/text",
    "github.com/hajimehoshi/ebiten/v2/vector",
]

## Set custom prefix for all symbols in the package (if applicable: see "no-prefix").
#custom-prefixes = [
#  ["my-fyne", "fyne.io/fyne/v2"],
#  ["my-widget", "fyne.io/fyne/v2/widget"],
#]
